version: '3.8'

services:
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: symfony_docker
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database